name: CI-pnpm-monorepo

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'
    paths-ignore:
      - 'examples/**'
      - 'docs/**'

permissions:
  contents: read

jobs:
  install-pnpm-monorepo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch all git history to allow running --since, turbo, nx...
          # @link https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
          fetch-depth: 0

      - name: ⚙️ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 PNPM monorepo install
        uses: ./.github/actions/pnpm-install
        with:
          cwd: ${{ github.workspace }}/pnpm-monorepo

      - name: 📥 PNPM monorepo install (corepack)
        uses: ./.github/actions/pnpm-install
        with:
          cwd: ${{ github.workspace }}/pnpm-monorepo
          enable-corepack: true